"use client";

import * as React from "react";
import { Download, Eye, FileText, Printer } from "lucide-react";
import type { Company, Market, ReportType } from "@/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input, Label, Select } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/misc";
import { Badge } from "@/components/ui/badge";
import { IllustrativeBadge } from "@/components/shared/illustrative";
import { getCountry } from "@/data/mock/countries";
import { useToast } from "@/components/shared/toast";

const reportTypes: { id: ReportType; label: string }[] = [
  { id: "market-entry", label: "Market-entry report" },
  { id: "buyer-shortlist", label: "Buyer shortlist" },
  { id: "supplier-assessment", label: "Supplier assessment" },
  { id: "country-comparison", label: "Country comparison" },
  { id: "price-analysis", label: "Price analysis" },
  { id: "competitor", label: "Competitor report" },
  { id: "shipment-summary", label: "Shipment summary" },
];

const sectionOptions = [
  "Overview",
  "Opportunity explanation",
  "Buyers",
  "Suppliers",
  "Markets",
  "Prices",
  "Charts",
  "Recommended actions",
];

export function ReportBuilder({
  companies,
  markets,
}: {
  companies: Company[];
  markets: Market[];
}) {
  const { toast } = useToast();
  const [type, setType] = React.useState<ReportType>("market-entry");
  const [title, setTitle] = React.useState("Natural honey — UAE market entry");
  const [product, setProduct] = React.useState("Natural honey");
  const [hsCode, setHsCode] = React.useState("0409");
  const [dateRange, setDateRange] = React.useState("Last 12 months");
  const [sections, setSections] = React.useState<string[]>([
    "Overview",
    "Opportunity explanation",
    "Buyers",
    "Recommended actions",
  ]);
  const [companyIds, setCompanyIds] = React.useState<string[]>(
    companies.slice(0, 3).map((c) => c.id),
  );
  const [marketIds, setMarketIds] = React.useState<string[]>(
    markets.slice(0, 2).map((m) => m.id),
  );
  const [preview, setPreview] = React.useState(false);

  const toggle = (
    setter: React.Dispatch<React.SetStateAction<string[]>>,
    value: string,
  ) =>
    setter((prev) =>
      prev.includes(value) ? prev.filter((x) => x !== value) : [...prev, value],
    );

  function downloadMarkdown() {
    const chosenCompanies = companies.filter((c) => companyIds.includes(c.id));
    const chosenMarkets = markets.filter((m) => marketIds.includes(m.id));
    const md = [
      `# ${title}`,
      ``,
      `> ILLUSTRATIVE DEMO REPORT — not based on live or verified data.`,
      ``,
      `**Type:** ${reportTypes.find((r) => r.id === type)?.label}`,
      `**Product:** ${product}  `,
      `**HS code:** ${hsCode}  `,
      `**Period:** ${dateRange}`,
      ``,
      `## Sections`,
      ...sections.map((s) => `- ${s}`),
      ``,
      `## Markets`,
      ...chosenMarkets.map(
        (m) =>
          `- ${getCountry(m.countryCode)?.name}: score ${m.opportunity.value}/100, ${m.trend}, ${m.growth}% illustrative YoY`,
      ),
      ``,
      `## Companies`,
      ...chosenCompanies.map(
        (c) =>
          `- ${c.name} (${c.role}, ${getCountry(c.countryCode)?.name}) — score ${c.opportunity.value}/100`,
      ),
      ``,
      `_Generated by Vaskodigama (demonstration)._`,
    ].join("\n");

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "-").toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Report downloaded (demo)", description: "A local Markdown file was created.", tone: "success" });
  }

  return (
    <div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]">
      <Card>
        <CardHeader>
          <CardTitle as="h2">Build a report</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label htmlFor="rb-type" className="mb-1 block">Report type</Label>
            <Select id="rb-type" value={type} onChange={(e) => setType(e.target.value as ReportType)}>
              {reportTypes.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.label}
                </option>
              ))}
            </Select>
          </div>
          <div>
            <Label htmlFor="rb-title" className="mb-1 block">Title</Label>
            <Input id="rb-title" value={title} onChange={(e) => setTitle(e.target.value)} />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="rb-product" className="mb-1 block">Product</Label>
              <Input id="rb-product" value={product} onChange={(e) => setProduct(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="rb-hs" className="mb-1 block">HS code</Label>
              <Input id="rb-hs" value={hsCode} onChange={(e) => setHsCode(e.target.value)} />
            </div>
          </div>
          <div>
            <Label htmlFor="rb-range" className="mb-1 block">Date range</Label>
            <Select id="rb-range" value={dateRange} onChange={(e) => setDateRange(e.target.value)}>
              {["Last 30 days", "Last 3 months", "Last 6 months", "Last 12 months"].map((d) => (
                <option key={d} value={d}>
                  {d}
                </option>
              ))}
            </Select>
          </div>

          <fieldset>
            <legend className="mb-1.5 text-sm font-medium text-muted-strong">Sections</legend>
            <div className="grid grid-cols-2 gap-2">
              {sectionOptions.map((s) => (
                <Checkbox
                  key={s}
                  checked={sections.includes(s)}
                  onChange={() => toggle(setSections, s)}
                  label={s}
                />
              ))}
            </div>
          </fieldset>

          <fieldset>
            <legend className="mb-1.5 text-sm font-medium text-muted-strong">Include markets</legend>
            <div className="space-y-1.5">
              {markets.map((m) => (
                <Checkbox
                  key={m.id}
                  checked={marketIds.includes(m.id)}
                  onChange={() => toggle(setMarketIds, m.id)}
                  label={getCountry(m.countryCode)?.name ?? m.countryCode}
                />
              ))}
            </div>
          </fieldset>

          <fieldset>
            <legend className="mb-1.5 text-sm font-medium text-muted-strong">Include companies</legend>
            <div className="space-y-1.5">
              {companies.slice(0, 6).map((c) => (
                <Checkbox
                  key={c.id}
                  checked={companyIds.includes(c.id)}
                  onChange={() => toggle(setCompanyIds, c.id)}
                  label={c.name}
                />
              ))}
            </div>
          </fieldset>

          <div className="flex flex-wrap gap-2 pt-2">
            <Button onClick={() => setPreview(true)}>
              <Eye className="size-4" aria-hidden /> Preview
            </Button>
            <Button variant="outline" onClick={downloadMarkdown}>
              <Download className="size-4" aria-hidden /> Download (demo)
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Preview */}
      <Card>
        <CardHeader className="flex-row items-center justify-between">
          <CardTitle as="h2">Preview</CardTitle>
          <div className="flex items-center gap-2">
            <IllustrativeBadge />
            <Button variant="ghost" size="sm" onClick={() => window.print()}>
              <Printer className="size-4" aria-hidden /> Print
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {!preview ? (
            <div className="flex flex-col items-center justify-center rounded-lg border border-dashed border-border-strong bg-surface px-6 py-16 text-center">
              <FileText className="size-8 text-muted" aria-hidden />
              <p className="mt-2 text-sm text-muted">
                Configure the report and select “Preview” to see it here.
              </p>
            </div>
          ) : (
            <article className="space-y-4">
              <header>
                <p className="text-xs font-semibold uppercase tracking-wide text-primary">
                  {reportTypes.find((r) => r.id === type)?.label}
                </p>
                <h3 className="text-xl font-bold text-navy">{title}</h3>
                <p className="text-sm text-muted">
                  {product} · HS {hsCode} · {dateRange}
                </p>
              </header>

              {sections.includes("Overview") ? (
                <section>
                  <h4 className="font-semibold text-navy">Overview</h4>
                  <p className="text-sm text-muted">
                    This illustrative report summarises selected markets and
                    companies for {product}. Figures are estimates for
                    demonstration and are not verified.
                  </p>
                </section>
              ) : null}

              {sections.includes("Markets") || sections.includes("Opportunity explanation") ? (
                <section>
                  <h4 className="font-semibold text-navy">Markets</h4>
                  <ul className="mt-1 space-y-1 text-sm text-muted">
                    {markets
                      .filter((m) => marketIds.includes(m.id))
                      .map((m) => (
                        <li key={m.id} className="flex items-center justify-between">
                          <span>{getCountry(m.countryCode)?.name}</span>
                          <Badge tone="primary">{m.opportunity.value}/100</Badge>
                        </li>
                      ))}
                  </ul>
                </section>
              ) : null}

              {sections.includes("Buyers") || sections.includes("Suppliers") ? (
                <section>
                  <h4 className="font-semibold text-navy">Companies</h4>
                  <ul className="mt-1 space-y-1 text-sm text-muted">
                    {companies
                      .filter((c) => companyIds.includes(c.id))
                      .map((c) => (
                        <li key={c.id} className="flex items-center justify-between">
                          <span>
                            {c.name}{" "}
                            <span className="capitalize text-muted">({c.role})</span>
                          </span>
                          <Badge tone="neutral">{c.opportunity.value}/100</Badge>
                        </li>
                      ))}
                  </ul>
                </section>
              ) : null}

              {sections.includes("Recommended actions") ? (
                <section>
                  <h4 className="font-semibold text-navy">Recommended actions</h4>
                  <ul className="mt-1 list-disc space-y-1 pl-4 text-sm text-muted">
                    <li>Shortlist the top two suppliers and compare pricing.</li>
                    <li>Set a price alert for the selected market.</li>
                    <li>Prepare outreach to the most active buyer.</li>
                  </ul>
                </section>
              ) : null}

              <footer className="border-t border-border pt-3 text-xs text-muted">
                Generated by Vaskodigama (demonstration). Illustrative data only.
              </footer>
            </article>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
